- name: create directories
  file:
    path: "{{item}}"
    owner: "{{veradev_user}}"
    group: "{{veradev_group}}"
    mode: 0770
    state: directory
  with_items:
  - "{{veradev_path}}/bin"
  - "{{veradev_path}}/tmp"
  when: '"veradev" in dotfile_contexts'
- name: veradev profile hook
  template:
    src: "veradev-profile"
    dest: "{{veradev_hook_path}}/.veradev"
    owner: "{{veradev_user}}"
    group: "{{veradev_group}}"
    mode: 0600
  when: '"veradev" in dotfile_contexts'
- name: copy scripts
  copy:
    src: "{{item}}.sh"
    dest: "{{veradev_path}}/bin/{{item}}"
    owner: "{{veradev_user}}"
    group: "{{veradev_group}}"
    mode: 0700
  with_items: "{{veradev_scripts}}"
  when: '"veradev" in dotfile_contexts'
- name: mirror dkjson
  get_url:
    url: "https://raw.githubusercontent.com/LuaDist/dkjson/master/dkjson.lua"
    dest: "{{veradev_path}}/tmp/dkjson.lua"
    owner: "{{veradev_user}}"
    group: "{{veradev_group}}"
    mode: 0600
  when: '"veradev" in dotfile_contexts'
